-- Check row counts for key tables
SELECT 'Users' as table_name, count(*) as rows FROM "Users"
UNION ALL SELECT 'Roles', count(*) FROM "Roles"
UNION ALL SELECT 'UserRoles', count(*) FROM "UserRoles"
UNION ALL SELECT 'Buildings', count(*) FROM "Buildings"
UNION ALL SELECT 'Locations', count(*) FROM "Locations"
UNION ALL SELECT 'Assets', count(*) FROM "Assets"
UNION ALL SELECT 'WorkOrders', count(*) FROM "WorkOrders"
UNION ALL SELECT 'MaintenanceTemplates', count(*) FROM "MaintenanceTemplates"
UNION ALL SELECT 'MaintenanceChecklistTemplates', count(*) FROM "MaintenanceChecklistTemplates"
UNION ALL SELECT 'MaintenanceChecklistItems', count(*) FROM "MaintenanceChecklistItems"
UNION ALL SELECT 'Services', count(*) FROM "Services"
UNION ALL SELECT 'Purchases', count(*) FROM "Purchases"
UNION ALL SELECT 'InventoryItems', count(*) FROM "InventoryItems"
UNION ALL SELECT 'SystemSettings', count(*) FROM "SystemSettings"
UNION ALL SELECT 'ActivityLogs', count(*) FROM "ActivityLogs"
UNION ALL SELECT 'FileAttachments', count(*) FROM "FileAttachments"
ORDER BY table_name;
